# ============================================================
# Conexion con PostgreSQL - Docker
# ============================================================

# Desde el contenedor de Spring Boot, "postgres" identifica
# al servicio PostgreSQL definido en Docker Compose.
spring.datasource.url=jdbc:postgresql://postgres:5432/empleados

# Usuario de PostgreSQL.
spring.datasource.username=postgres

# Contraseña del usuario de PostgreSQL.
spring.datasource.password=postgres

# Driver JDBC utilizado para conectar con PostgreSQL.
spring.datasource.driver-class-name=org.postgresql.Driver