# ============================================================
# Conexion con PostgreSQL - Eclipse
# ============================================================

# Desde Eclipse, Spring Boot se ejecuta directamente en Windows.
# PostgreSQL esta disponible mediante el puerto publicado por Docker.
spring.datasource.url=jdbc:postgresql://localhost:5432/empleados

spring.datasource.username=postgres
spring.datasource.password=postgres

# Driver JDBC de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver