spring.application.name=CodeJa_SpringBootBasico

# ============================================================
# JPA / Hibernate
# ============================================================

# Crea las tablas al arrancar y las actualiza si cambia la Entity.
spring.jpa.hibernate.ddl-auto=update

# Muestra en consola las sentencias SQL ejecutadas por Hibernate.
spring.jpa.show-sql=true