spring.application.name=CodeJa_SpringBootBasico

# ============================================================
# Conexion con PostgreSQL
# ============================================================

spring.datasource.url=jdbc:postgresql://postgres:5432/empleados
spring.datasource.username=postgres
spring.datasource.password=postgres

# Driver JDBC de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver


# ============================================================
# JPA / Hibernate
# ============================================================

# Crea las tablas al arrancar y las actualiza si cambia la Entity.
spring.jpa.hibernate.ddl-auto=update

# Muestra en consola las sentencias SQL ejecutadas por Hibernate.
spring.jpa.show-sql=true